stages:
  - test
  - build
  - deploy:images
  - deploy:pypi
  - deploy:docs

test:
  script:
    - make bootstrap-dev
    - make test

build:images:
  script:
    - make ci-bootstrap-images
    - tutor images build all
  stage: build

build:docs:
  script:
    - pip install -r requirements/docs.txt
    - make docs
  artifacts:
    paths:
      - docs/_build/html
  stage: build

build:pypi:
  script:
    - make bootstrap-dev
    - make build-pythonpackage
  artifacts:
    paths:
      - dist/
  stage: build

deploy:images:
  script:
    - make ci-bootstrap-images
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
    - tutor images push all
  only:
    - tags
  stage: deploy:images

deploy:pypi:
  script:
    - make push-pythonpackage
  dependencies:
    - build:pypi
  only:
    - tags
  stage: deploy:pypi

deploy:docs:
  dependencies:
    - build:docs
  script:
    - rm -rf /var/www/docs.tutor.overhang.io
    - mv docs/_build/html/ /var/www/docs.tutor.overhang.io
  only:
    - tags
  tags:
    - private
  stage: deploy:docs
